<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InvestmentPlanSeeder extends Seeder
{
    /**
     * Seed practical demo investment products.
     *
     * Values are stable QA fixtures, not financial advice or live market data.
     */
    public function run(): void
    {
        $now = now();

        $plans = [
            [
                'name' => 'Tesla Growth Fund',
                'description' => 'High-growth thematic portfolio focused on electric mobility, battery technology, autonomous systems, and adjacent growth companies.',
                'type' => 'tesla_focused',
                'category' => 'Tesla-Focused',
                'risk_level' => 'high',
                'minimum_investment' => 100.00,
                'management_fee' => 0.0085,
                'expense_ratio' => 0.0090,
                'nav' => 25.5000,
                'previous_nav' => 25.1200,
                'nav_change' => 0.3800,
                'nav_change_percentage' => 1.51,
                'total_assets' => 2500000.00,
                'inception_date' => '2020-01-15',
                'dividend_yield' => 0.40,
                'is_active' => true,
                'is_featured' => true,
                'image' => '/tesla.png',
                'prospectus_url' => null,
                'fact_sheet_url' => null,
                'last_updated' => $now,
            ],
            [
                'name' => 'Sustainable Energy ETF',
                'description' => 'Diversified clean-energy basket spanning renewable generation, grid infrastructure, storage, and energy-efficiency businesses.',
                'type' => 'etf',
                'category' => 'ESG',
                'risk_level' => 'medium',
                'minimum_investment' => 50.00,
                'management_fee' => 0.0045,
                'expense_ratio' => 0.0055,
                'nav' => 18.7500,
                'previous_nav' => 18.6200,
                'nav_change' => 0.1300,
                'nav_change_percentage' => 0.70,
                'total_assets' => 1800000.00,
                'inception_date' => '2019-06-20',
                'dividend_yield' => 1.25,
                'is_active' => true,
                'is_featured' => true,
                'image' => null,
                'prospectus_url' => null,
                'fact_sheet_url' => null,
                'last_updated' => $now,
            ],
            [
                'name' => 'Tesla Retirement Fund',
                'description' => 'Long-horizon retirement portfolio combining broad-market exposure with a controlled allocation to electric-mobility growth.',
                'type' => 'retirement',
                'category' => 'Conservative',
                'risk_level' => 'low',
                'minimum_investment' => 250.00,
                'management_fee' => 0.0050,
                'expense_ratio' => 0.0060,
                'nav' => 15.2000,
                'previous_nav' => 15.1600,
                'nav_change' => 0.0400,
                'nav_change_percentage' => 0.26,
                'total_assets' => 3200000.00,
                'inception_date' => '2021-03-10',
                'dividend_yield' => 2.10,
                'is_active' => true,
                'is_featured' => false,
                'image' => null,
                'prospectus_url' => null,
                'fact_sheet_url' => null,
                'last_updated' => $now,
            ],
            [
                'name' => 'Conservative Income Fund',
                'description' => 'Income-oriented mutual fund designed around capital preservation, dividend-paying companies, and lower-volatility assets.',
                'type' => 'mutual_fund',
                'category' => 'Income',
                'risk_level' => 'low',
                'minimum_investment' => 500.00,
                'management_fee' => 0.0045,
                'expense_ratio' => 0.0055,
                'nav' => 12.8000,
                'previous_nav' => 12.7600,
                'nav_change' => 0.0400,
                'nav_change_percentage' => 0.31,
                'total_assets' => 4500000.00,
                'inception_date' => '2018-09-05',
                'dividend_yield' => 3.40,
                'is_active' => true,
                'is_featured' => false,
                'image' => null,
                'prospectus_url' => null,
                'fact_sheet_url' => null,
                'last_updated' => $now,
            ],
            [
                'name' => 'Aggressive Growth Fund',
                'description' => 'High-volatility growth portfolio targeting innovative technology, automation, semiconductors, and emerging market leaders.',
                'type' => 'mutual_fund',
                'category' => 'Growth',
                'risk_level' => 'very_high',
                'minimum_investment' => 200.00,
                'management_fee' => 0.0095,
                'expense_ratio' => 0.0100,
                'nav' => 32.4000,
                'previous_nav' => 31.8500,
                'nav_change' => 0.5500,
                'nav_change_percentage' => 1.73,
                'total_assets' => 1800000.00,
                'inception_date' => '2020-11-12',
                'dividend_yield' => 0.20,
                'is_active' => true,
                'is_featured' => true,
                'image' => null,
                'prospectus_url' => null,
                'fact_sheet_url' => null,
                'last_updated' => $now,
            ],
            [
                'name' => 'ESG Balanced Fund',
                'description' => 'Balanced ESG portfolio blending quality equities, sustainable infrastructure, and defensive income assets.',
                'type' => 'esg',
                'category' => 'Balanced',
                'risk_level' => 'medium',
                'minimum_investment' => 150.00,
                'management_fee' => 0.0060,
                'expense_ratio' => 0.0068,
                'nav' => 22.1500,
                'previous_nav' => 22.0300,
                'nav_change' => 0.1200,
                'nav_change_percentage' => 0.54,
                'total_assets' => 2100000.00,
                'inception_date' => '2021-07-22',
                'dividend_yield' => 1.80,
                'is_active' => true,
                'is_featured' => true,
                'image' => null,
                'prospectus_url' => null,
                'fact_sheet_url' => null,
                'last_updated' => $now,
            ],
            [
                'name' => 'Tesla Technology Fund',
                'description' => 'Concentrated technology strategy focused on EV software, autonomous driving, AI infrastructure, robotics, and battery innovation.',
                'type' => 'tesla_focused',
                'category' => 'Tesla-Focused',
                'risk_level' => 'very_high',
                'minimum_investment' => 300.00,
                'management_fee' => 0.0090,
                'expense_ratio' => 0.0095,
                'nav' => 28.9000,
                'previous_nav' => 28.3000,
                'nav_change' => 0.6000,
                'nav_change_percentage' => 2.12,
                'total_assets' => 1200000.00,
                'inception_date' => '2022-02-14',
                'dividend_yield' => 0.10,
                'is_active' => true,
                'is_featured' => false,
                'image' => '/tesla.png',
                'prospectus_url' => null,
                'fact_sheet_url' => null,
                'last_updated' => $now,
            ],
            [
                'name' => 'Dividend Income Fund',
                'description' => 'Diversified portfolio of established dividend-paying companies intended to support recurring income and moderate appreciation.',
                'type' => 'mutual_fund',
                'category' => 'Income',
                'risk_level' => 'medium',
                'minimum_investment' => 1000.00,
                'management_fee' => 0.0055,
                'expense_ratio' => 0.0060,
                'nav' => 14.6000,
                'previous_nav' => 14.5400,
                'nav_change' => 0.0600,
                'nav_change_percentage' => 0.41,
                'total_assets' => 3800000.00,
                'inception_date' => '2019-12-03',
                'dividend_yield' => 4.10,
                'is_active' => true,
                'is_featured' => false,
                'image' => null,
                'prospectus_url' => null,
                'fact_sheet_url' => null,
                'last_updated' => $now,
            ],
            [
                'name' => 'Global Growth Index',
                'description' => 'Broad index-style strategy tracking large and mid-cap growth companies across major developed markets.',
                'type' => 'index_fund',
                'category' => 'Growth',
                'risk_level' => 'medium',
                'minimum_investment' => 100.00,
                'management_fee' => 0.0025,
                'expense_ratio' => 0.0030,
                'nav' => 19.8000,
                'previous_nav' => 19.6600,
                'nav_change' => 0.1400,
                'nav_change_percentage' => 0.71,
                'total_assets' => 6900000.00,
                'inception_date' => '2020-08-18',
                'dividend_yield' => 1.45,
                'is_active' => true,
                'is_featured' => true,
                'image' => null,
                'prospectus_url' => null,
                'fact_sheet_url' => null,
                'last_updated' => $now,
            ],
            [
                'name' => 'Conservative Bond Fund',
                'description' => 'Defensive fixed-income portfolio using government and investment-grade corporate bonds for stability and income.',
                'type' => 'mutual_fund',
                'category' => 'Conservative',
                'risk_level' => 'low',
                'minimum_investment' => 750.00,
                'management_fee' => 0.0035,
                'expense_ratio' => 0.0045,
                'nav' => 10.4500,
                'previous_nav' => 10.4300,
                'nav_change' => 0.0200,
                'nav_change_percentage' => 0.19,
                'total_assets' => 5200000.00,
                'inception_date' => '2017-05-30',
                'dividend_yield' => 4.60,
                'is_active' => true,
                'is_featured' => false,
                'image' => null,
                'prospectus_url' => null,
                'fact_sheet_url' => null,
                'last_updated' => $now,
            ],
        ];

        foreach ($plans as $plan) {
            $previous = (float) ($plan['previous_nav'] ?? $plan['nav']);
            $current = (float) $plan['nav'];
            $midpoint = round(($previous + $current) / 2, 4);
            $plan['nav_history'] = json_encode([
                ['date' => '2026-09-08', 'nav' => round($previous * 0.992, 4)],
                ['date' => '2026-09-09', 'nav' => round($previous * 0.997, 4)],
                ['date' => '2026-09-10', 'nav' => $previous],
                ['date' => '2026-09-11', 'nav' => $midpoint],
                ['date' => '2026-09-12', 'nav' => $current],
            ]);
            $plan['last_nav_update'] = '2026-09-12 20:00:00';

            DB::table('investment_plans')->updateOrInsert(
                ['name' => $plan['name']],
                array_merge($plan, [
                    'created_at' => $now,
                    'updated_at' => $now,
                ])
            );
        }
    }
}
