<x-user-layout><x-slot name="header">Copy Trading</x-slot><div class="ui-page max-w-[1440px]"><section class="ui-page-header"><div><p class="ui-kicker text-[10px]">Copy Trading</p><h1 class="ui-heading !text-xl">Strategy Marketplace</h1><p class="ui-lead !text-[13px]">Approved provider strategies with transparent performance and limits.</p></div><div class="flex gap-2"><a href="{{ route('copy-trading.my-copies') }}" class="ui-btn ui-btn-secondary"><i data-lucide="copy" class="h-4 w-4"></i> My Copies</a><a href="{{ route('copy-trading.apply') }}" class="ui-btn ui-btn-secondary"><i data-lucide="badge-check" class="h-4 w-4"></i> Become Provider</a></div></section><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">@forelse($strategies as $strategy)@php
    $m = $strategy->performance_metrics;
@endphp
@if($m['is_manual_performance'])
    <div class="mb-2 inline-flex items-center gap-1.5 rounded-full border border-violet-500/20 bg-violet-500/10 px-2 py-1 text-[9px] font-semibold uppercase tracking-[0.12em] text-violet-600">
        <i data-lucide="sparkles" class="h-3 w-3"></i>
        {{ $m['performance_label'] ?: 'Manual Performance' }}
    </div>
@endif
 <div class="ui-panel overflow-hidden border border-border/70 bg-gradient-to-br from-background via-background to-muted/10 p-4 shadow-sm"><div class="flex justify-between gap-3"><div><p class="text-xs text-muted-foreground">{{ $strategy->profile->user->name }}</p><h2 class="mt-1 text-base font-semibold">{{ $strategy->name }}</h2></div><span class="rounded-full border border-amber-500/20 bg-amber-500/10 px-2 py-1 text-[10px] font-semibold text-amber-600">{{ ucfirst($strategy->risk_level) }} risk</span></div><p class="mt-2 line-clamp-2 text-xs leading-5 text-muted-foreground">{{ $strategy->description }}</p><div class="mt-4 grid grid-cols-2 gap-2.5"><div class="rounded-xl border {{ $m['profit_loss']>0?'border-emerald-500/20 bg-emerald-500/5':'border-border' }} p-3"><p class="text-[10px] uppercase tracking-[.14em] text-muted-foreground">P/L</p><p class="mt-1 text-sm font-semibold {{ $m['profit_loss']>0?'text-emerald-600':'' }}">{{ $m['profit_loss']>0?'+':'' }}{{ format_currency($m['profit_loss']) }}</p></div><div class="rounded-xl border border-sky-500/20 bg-sky-500/5 p-3"><p class="text-[10px] uppercase tracking-[.14em] text-muted-foreground">Return</p><p class="mt-1 text-sm font-semibold text-sky-600">{{ $m['return_percent']>0?'+':'' }}{{ number_format($m['return_percent'],2) }}%</p></div><div class="rounded-xl border border-border p-3"><p class="text-[10px] uppercase tracking-[.14em] text-muted-foreground">Trades</p><p class="mt-1 text-sm font-semibold">{{ $m['completed_count'] }}</p></div><div class="rounded-xl border border-border p-3"><p class="text-[10px] uppercase tracking-[.14em] text-muted-foreground">Minimum</p><p class="mt-1 text-sm font-semibold">{{ format_currency($strategy->minimum_allocation) }}</p></div></div><form action="{{ route('copy-trading.follow',$strategy) }}" method="POST" class="mt-4 space-y-2.5 border-t border-border pt-4">@csrf<div><label class="ui-label !text-[11px]">Allocation</label><input name="allocation_limit" class="ui-input" type="number" min="{{ $strategy->minimum_allocation }}" value="{{ $strategy->recommended_allocation ?: $strategy->minimum_allocation }}"></div><div class="grid grid-cols-2 gap-2.5"><div><label class="ui-label !text-[11px]">Max / Trade</label><input name="max_trade_amount" class="ui-input" type="number" min="10" value="{{ $strategy->minimum_allocation }}"></div><div><label class="ui-label !text-[11px]">Copy %</label><input name="copy_ratio_percent" class="ui-input" type="number" min="1" max="200" value="100"></div></div><button class="ui-btn ui-btn-primary w-full"><i data-lucide="copy-check" class="h-4 w-4"></i> Copy Strategy</button></form></div>@empty<div class="ui-panel p-8 md:col-span-2 xl:col-span-3 text-center text-sm text-muted-foreground">No approved strategies available.</div>@endforelse</div></div></x-user-layout>