<x-admin-layout>
    <div class="ui-page max-w-[1500px] space-y-4">
        <section class="ui-panel p-5 sm:p-6"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div class="flex items-start gap-4"><div class="flex h-11 w-11 items-center justify-center rounded-xl border border-border bg-muted/40"><i data-lucide="activity" class="h-5 w-5"></i></div><div><p class="ui-kicker">Signal Engine</p><h1 class="mt-1 text-2xl font-semibold">Engine Activity</h1><p class="mt-1 text-sm text-muted-foreground">Analysis runs, lifecycle events and distribution batches in one audit workspace.</p></div></div><a href="{{ route('admin.signals.index') }}" class="ui-btn ui-btn-secondary"><i data-lucide="arrow-left" class="h-4 w-4"></i>Signal Desk</a></div></section>

        @include('admin.signals._nav')

        <section class="grid gap-4 xl:grid-cols-3">
            <article class="ui-panel overflow-hidden"><div class="border-b border-border px-5 py-4"><p class="ui-kicker">Lifecycle</p><h2 class="mt-1 font-semibold">Events</h2></div><div class="max-h-[720px] divide-y divide-border overflow-y-auto">@forelse($events as $event)<div class="px-5 py-4"><div class="flex items-start gap-3"><div class="mt-0.5 flex h-8 w-8 items-center justify-center rounded-lg bg-muted"><i data-lucide="git-commit-horizontal" class="h-4 w-4"></i></div><div class="min-w-0"><p class="text-xs font-semibold uppercase">{{ str_replace('_',' ', $event->type) }}</p><p class="mt-1 text-xs text-muted-foreground">#{{ $event->signal_id }} · {{ $event->signal?->instrument_symbol ?? 'Unknown' }} · {{ $event->occurred_at?->diffForHumans() }}</p>@if($event->actor)<p class="mt-1 text-[10px] text-muted-foreground">Actor: {{ $event->actor->name }}</p>@endif</div></div></div>@empty<div class="p-8 text-center text-xs text-muted-foreground">No events.</div>@endforelse</div></article>

            <article class="ui-panel overflow-hidden"><div class="border-b border-border px-5 py-4"><p class="ui-kicker">Intelligence</p><h2 class="mt-1 font-semibold">Analysis Runs</h2></div><div class="max-h-[720px] divide-y divide-border overflow-y-auto">@forelse($analysisRuns as $run)<div class="px-5 py-4"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-semibold">{{ $run->marketInstrument?->display_symbol ?? $run->signal?->instrument_symbol ?? $run->stock?->symbol ?? 'Unknown' }} · {{ strtoupper($run->marketplace) }}</p><p class="mt-1 text-[10px] uppercase text-muted-foreground">{{ str_replace('_',' ', $run->result) }} · {{ $run->trigger }}</p></div><div class="text-right"><p class="text-xs font-semibold">{{ $run->confluence_score !== null ? number_format((float)$run->confluence_score,2).'%' : '—' }}</p><p class="mt-1 text-[10px] text-muted-foreground">{{ $run->analyzed_at?->diffForHumans() }}</p></div></div></div>@empty<div class="p-8 text-center text-xs text-muted-foreground">No analyses.</div>@endforelse</div></article>

            <article class="ui-panel overflow-hidden"><div class="border-b border-border px-5 py-4"><p class="ui-kicker">Distribution</p><h2 class="mt-1 font-semibold">Delivery Batches</h2></div><div class="max-h-[720px] divide-y divide-border overflow-y-auto">@forelse($distributions as $distribution)<div class="px-5 py-4"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-semibold">{{ $distribution->signal?->instrument_symbol ?? 'Unknown' }} · {{ strtoupper($distribution->mode) }}</p><p class="mt-1 text-[10px] text-muted-foreground">Signal #{{ $distribution->signal_id }} · {{ $distribution->initiatedBy?->name ?? 'System' }}</p></div><div class="text-right"><p class="text-xs font-semibold">{{ $distribution->delivered_count }} delivered</p><p class="mt-1 text-[10px] text-muted-foreground">{{ $distribution->skipped_count }} skipped · {{ $distribution->failed_count }} failed</p></div></div></div>@empty<div class="p-8 text-center text-xs text-muted-foreground">No distribution batches.</div>@endforelse</div></article>
        </section>
    </div>
</x-admin-layout>
