<?php

return [
    'group' => 'finance',
    'terms' => [
        'available_balance' => ['identity' => 'finance.available_balance', 'fallback' => 'Available balance'],
        'balance' => ['identity' => 'finance.balance', 'fallback' => 'Balance'],
        'wallet_balance' => ['identity' => 'finance.wallet_balance', 'fallback' => 'Wallet balance'],
        'reserved_balance' => ['identity' => 'finance.reserved_balance', 'fallback' => 'Reserved balance'],
        'deposit' => ['identity' => 'finance.deposit', 'fallback' => 'Deposit'],
        'withdrawal' => ['identity' => 'finance.withdrawal', 'fallback' => 'Withdrawal'],
        'transfer' => ['identity' => 'finance.transfer', 'fallback' => 'Transfer'],
        'transaction' => ['identity' => 'finance.transaction', 'fallback' => 'Transaction'],
        'portfolio_value' => ['identity' => 'finance.portfolio_value', 'fallback' => 'Portfolio value'],
        'invested_capital' => ['identity' => 'finance.invested_capital', 'fallback' => 'Invested capital'],
        'holdings' => ['identity' => 'finance.holdings', 'fallback' => 'Holdings'],
        'position' => ['identity' => 'finance.position', 'fallback' => 'Position'],
        'open_position' => ['identity' => 'finance.open_position', 'fallback' => 'Open position'],
        'closed_position' => ['identity' => 'finance.closed_position', 'fallback' => 'Closed position'],
        'entry_price' => ['identity' => 'finance.entry_price', 'fallback' => 'Entry price'],
        'average_entry' => ['identity' => 'finance.average_entry', 'fallback' => 'Average entry'],
        'market_price' => ['identity' => 'finance.market_price', 'fallback' => 'Market price'],
        'quantity' => ['identity' => 'finance.quantity', 'fallback' => 'Quantity'],
        'stop_loss' => ['identity' => 'finance.stop_loss', 'fallback' => 'Stop loss'],
        'take_profit' => ['identity' => 'finance.take_profit', 'fallback' => 'Take profit'],
        'risk_reward' => ['identity' => 'finance.risk_reward', 'fallback' => 'Risk : Reward'],
        'realized_pnl' => ['identity' => 'finance.realized_pnl', 'fallback' => 'Realized P/L'],
        'unrealized_pnl' => ['identity' => 'finance.unrealized_pnl', 'fallback' => 'Unrealized P/L'],
        'profit_loss' => ['identity' => 'finance.profit_loss', 'fallback' => 'Profit / Loss'],
        'buying_power' => ['identity' => 'finance.buying_power', 'fallback' => 'Buying power'],
        'equity' => ['identity' => 'finance.equity', 'fallback' => 'Equity'],
        'margin' => ['identity' => 'finance.margin', 'fallback' => 'Margin'],
        'free_margin' => ['identity' => 'finance.free_margin', 'fallback' => 'Free margin'],
        'used_margin' => ['identity' => 'finance.used_margin', 'fallback' => 'Used margin'],
        'leverage' => ['identity' => 'finance.leverage', 'fallback' => 'Leverage'],
        'execution' => ['identity' => 'finance.execution', 'fallback' => 'Execution'],
        'broker_order' => ['identity' => 'finance.broker_order', 'fallback' => 'Broker order'],
        'market_order' => ['identity' => 'finance.market_order', 'fallback' => 'Market order'],
        'limit_order' => ['identity' => 'finance.limit_order', 'fallback' => 'Limit order'],
        'buy' => ['identity' => 'finance.buy', 'fallback' => 'Buy'],
        'sell' => ['identity' => 'finance.sell', 'fallback' => 'Sell'],
        'signal' => ['identity' => 'finance.signal', 'fallback' => 'Signal'],
        'signal_strength' => ['identity' => 'finance.signal_strength', 'fallback' => 'Signal strength'],
        'confluence' => ['identity' => 'finance.confluence', 'fallback' => 'Confluence'],
        'target' => ['identity' => 'finance.target', 'fallback' => 'Target'],
        'investment_maturity' => ['identity' => 'finance.investment_maturity', 'fallback' => 'Investment maturity'],
        'principal' => ['identity' => 'finance.principal', 'fallback' => 'Principal'],
        'return' => ['identity' => 'finance.return', 'fallback' => 'Return'],
        'allocation' => ['identity' => 'finance.allocation', 'fallback' => 'Allocation'],
        'processing_fee' => ['identity' => 'finance.processing_fee', 'fallback' => 'Processing fee'],
        'payout' => ['identity' => 'finance.payout', 'fallback' => 'Payout'],
    ],
];
