<?php

return [
    'default' => 'en',
    'fallback' => 'en',
    'bundle_files' => [
        'localization_core.php',
        'localization_financial.php',
        'localization_interface_r2.php',
        'localization_money_operations_r2b.php',
        'localization_trading_signals_r2c.php',
        'localization_investments_bots_copy_r2d.php',
        'localization_final_surfaces_rtl_r2e.php',
        'localization_homepage_r3.php',
        'localization_investment_hedges_r3.php',
    ],
    'protected_groups' => ['finance'],
    'major_locales' => ['en','fr','es','pt','ar','zh-CN','de'],
    'languages' => [
        'en' => [
            'name' => 'English',
            'native_name' => 'English',
            'direction' => 'ltr',
            'major' => true,
            'sort_order' => 1,
        ],
        'fr' => [
            'name' => 'French',
            'native_name' => 'Français',
            'direction' => 'ltr',
            'major' => true,
            'sort_order' => 2,
        ],
        'es' => [
            'name' => 'Spanish',
            'native_name' => 'Español',
            'direction' => 'ltr',
            'major' => true,
            'sort_order' => 3,
        ],
        'pt' => [
            'name' => 'Portuguese',
            'native_name' => 'Português',
            'direction' => 'ltr',
            'major' => true,
            'sort_order' => 4,
        ],
        'ar' => [
            'name' => 'Arabic',
            'native_name' => 'العربية',
            'direction' => 'rtl',
            'major' => true,
            'sort_order' => 5,
        ],
        'zh-CN' => [
            'name' => 'Chinese (Simplified)',
            'native_name' => '简体中文',
            'direction' => 'ltr',
            'major' => true,
            'sort_order' => 6,
        ],
        'de' => [
            'name' => 'German',
            'native_name' => 'Deutsch',
            'direction' => 'ltr',
            'major' => true,
            'sort_order' => 7,
        ],
        'it' => [
            'name' => 'Italian',
            'native_name' => 'Italiano',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 8,
        ],
        'nl' => [
            'name' => 'Dutch',
            'native_name' => 'Nederlands',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 9,
        ],
        'pl' => [
            'name' => 'Polish',
            'native_name' => 'Polski',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 10,
        ],
        'ro' => [
            'name' => 'Romanian',
            'native_name' => 'Română',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 11,
        ],
        'ru' => [
            'name' => 'Russian',
            'native_name' => 'Русский',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 12,
        ],
        'uk' => [
            'name' => 'Ukrainian',
            'native_name' => 'Українська',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 13,
        ],
        'tr' => [
            'name' => 'Turkish',
            'native_name' => 'Türkçe',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 14,
        ],
        'el' => [
            'name' => 'Greek',
            'native_name' => 'Ελληνικά',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 15,
        ],
        'he' => [
            'name' => 'Hebrew',
            'native_name' => 'עברית',
            'direction' => 'rtl',
            'major' => false,
            'sort_order' => 16,
        ],
        'fa' => [
            'name' => 'Persian',
            'native_name' => 'فارسی',
            'direction' => 'rtl',
            'major' => false,
            'sort_order' => 17,
        ],
        'hi' => [
            'name' => 'Hindi',
            'native_name' => 'हिन्दी',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 18,
        ],
        'bn' => [
            'name' => 'Bengali',
            'native_name' => 'বাংলা',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 19,
        ],
        'ur' => [
            'name' => 'Urdu',
            'native_name' => 'اردو',
            'direction' => 'rtl',
            'major' => false,
            'sort_order' => 20,
        ],
        'pa' => [
            'name' => 'Punjabi',
            'native_name' => 'ਪੰਜਾਬੀ',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 21,
        ],
        'ta' => [
            'name' => 'Tamil',
            'native_name' => 'தமிழ்',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 22,
        ],
        'te' => [
            'name' => 'Telugu',
            'native_name' => 'తెలుగు',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 23,
        ],
        'mr' => [
            'name' => 'Marathi',
            'native_name' => 'मराठी',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 24,
        ],
        'gu' => [
            'name' => 'Gujarati',
            'native_name' => 'ગુજરાતી',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 25,
        ],
        'id' => [
            'name' => 'Indonesian',
            'native_name' => 'Bahasa Indonesia',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 26,
        ],
        'ms' => [
            'name' => 'Malay',
            'native_name' => 'Bahasa Melayu',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 27,
        ],
        'fil' => [
            'name' => 'Filipino',
            'native_name' => 'Filipino',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 28,
        ],
        'vi' => [
            'name' => 'Vietnamese',
            'native_name' => 'Tiếng Việt',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 29,
        ],
        'th' => [
            'name' => 'Thai',
            'native_name' => 'ไทย',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 30,
        ],
        'ja' => [
            'name' => 'Japanese',
            'native_name' => '日本語',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 31,
        ],
        'ko' => [
            'name' => 'Korean',
            'native_name' => '한국어',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 32,
        ],
        'sw' => [
            'name' => 'Swahili',
            'native_name' => 'Kiswahili',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 33,
        ],
        'ha' => [
            'name' => 'Hausa',
            'native_name' => 'Hausa',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 34,
        ],
        'yo' => [
            'name' => 'Yoruba',
            'native_name' => 'Yorùbá',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 35,
        ],
        'ig' => [
            'name' => 'Igbo',
            'native_name' => 'Igbo',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 36,
        ],
        'af' => [
            'name' => 'Afrikaans',
            'native_name' => 'Afrikaans',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 37,
        ],
        'zu' => [
            'name' => 'Zulu',
            'native_name' => 'isiZulu',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 38,
        ],
        'xh' => [
            'name' => 'Xhosa',
            'native_name' => 'isiXhosa',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 39,
        ],
        'am' => [
            'name' => 'Amharic',
            'native_name' => 'አማርኛ',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 40,
        ],
        'so' => [
            'name' => 'Somali',
            'native_name' => 'Soomaali',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 41,
        ],
        'ne' => [
            'name' => 'Nepali',
            'native_name' => 'नेपाली',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 42,
        ],
        'si' => [
            'name' => 'Sinhala',
            'native_name' => 'සිංහල',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 43,
        ],
        'km' => [
            'name' => 'Khmer',
            'native_name' => 'ខ្មែរ',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 44,
        ],
        'lo' => [
            'name' => 'Lao',
            'native_name' => 'ລາວ',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 45,
        ],
        'my' => [
            'name' => 'Burmese',
            'native_name' => 'မြန်မာ',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 46,
        ],
        'cs' => [
            'name' => 'Czech',
            'native_name' => 'Čeština',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 47,
        ],
        'sk' => [
            'name' => 'Slovak',
            'native_name' => 'Slovenčina',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 48,
        ],
        'hu' => [
            'name' => 'Hungarian',
            'native_name' => 'Magyar',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 49,
        ],
        'bg' => [
            'name' => 'Bulgarian',
            'native_name' => 'Български',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 50,
        ],
        'sr' => [
            'name' => 'Serbian',
            'native_name' => 'Српски',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 51,
        ],
        'hr' => [
            'name' => 'Croatian',
            'native_name' => 'Hrvatski',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 52,
        ],
        'da' => [
            'name' => 'Danish',
            'native_name' => 'Dansk',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 53,
        ],
        'sv' => [
            'name' => 'Swedish',
            'native_name' => 'Svenska',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 54,
        ],
        'no' => [
            'name' => 'Norwegian',
            'native_name' => 'Norsk',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 55,
        ],
        'fi' => [
            'name' => 'Finnish',
            'native_name' => 'Suomi',
            'direction' => 'ltr',
            'major' => false,
            'sort_order' => 56,
        ],
    ],
];
